// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrfuMaps.Api;

namespace UrfuMaps.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211210074545_bas")]
    partial class bas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("UrfuMaps.Api.Models.FloorScheme", b =>
                {
                    b.Property<int?>("FloorNumber")
                        .HasColumnType("integer");

                    b.Property<string>("BuildingName")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ImageLink")
                        .HasColumnType("text");

                    b.HasKey("FloorNumber", "BuildingName");

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("UrfuMaps.Api.Models.PositionScheme", b =>
                {
                    b.Property<string>("Cabinet")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("BuildingName")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("FloorNumber")
                        .HasColumnType("integer");

                    b.Property<double?>("X")
                        .HasColumnType("double precision");

                    b.Property<double?>("Y")
                        .HasColumnType("double precision");

                    b.HasKey("Cabinet");

                    b.HasIndex("FloorNumber", "BuildingName");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("UrfuMaps.Api.Models.User", b =>
                {
                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Login");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UrfuMaps.Api.Models.PositionScheme", b =>
                {
                    b.HasOne("UrfuMaps.Api.Models.FloorScheme", null)
                        .WithMany("Positions")
                        .HasForeignKey("FloorNumber", "BuildingName");
                });

            modelBuilder.Entity("UrfuMaps.Api.Models.FloorScheme", b =>
                {
                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
